### ISSUE TITLE
chk your email

### ISSUE THREAD

**Issue by tbhaxor** [arnavb/cpp14-project-template#4]
just check your email for once
sent from: tbhaxor@gmail.com
sent to: arnavborborah11@gmail.com

**Comment by arnavb** [comment]
@tbhaxor I will check my email, but please refrain from opening issues on projects completely irrelevant from your goals. I have been busy with school lately, which is why I haven't been active.

**Comment by tbhaxor** [comment]
@arnavb  i am extremely sorry :disappointed:
